version: "3.9"

networks:

  network-services_things-net:
    external: true

services:

  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2023.7.3"
    volumes:
      - ${DATA_STORAGE}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
    #   - /dev/ttyACMO  # (optional) Add serial devices to the container
      - ${ZIGBEE_DEVICE}
    privileged: true
    restart: unless-stopped
    networks:
      network-services_things-net:
        ipv4_address: ${HOMEASSISTANT_IP_ADDRESS}
    dns:
      - ${THINGS_PIHOLE_IP_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`home.${DOMAIN}`)
      - traefik.http.routers.homeassistant.tls.certresolver=certificato
      - traefik.http.routers.homeassistant.entrypoints=web,web-secure
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123