version: "3.9"

networks:
  01-transit_80-net:
    driver: macvlan # Otherwise PiHole and other containers cannot resolve DNS internally due to NAT issue within Docker
    # driver: ipvlan
    driver_opts:
      parent: enp8s0.${METAL_VLAN_ID}
      name: macvlan${METAL_VLAN_ID}
    ipam:
      config:
        - subnet: 10.100.${METAL_VLAN_ID}.0/24
          gateway: 10.100.${METAL_VLAN_ID}.2
          ip_range: 10.100.${METAL_VLAN_ID}.192/26 # 192-255
          # aux_addresses:
          #   reserved: 10.100.${METAL_VLAN_ID}.1
          #   dns: 10.100.${METAL_VLAN_ID}.3

  traefik_proxy:
    driver: bridge
    internal: true

  metrics-net:
    driver: bridge

services:
  do-nothing:
    image: jhnrn/do-nothing:latest
    restart: unless-stopped
    network_mode: none
