version: '3'

volumes:
  nextcloud-html:
    external: true
  nextcloud-db:
    external: true
  nextcloud-data:
    external: true

services:
  nextcloud-db:
    image: mariadb
    restart: always
    networks:
      - backend
    expose:
      - "3306"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-user

  nextcloud-app:
    image: nextcloud
    restart: always
    networks:
      frontend:
          ipv4_address: "10.100.60.49"
      backend:
    ports:
      - 8080:80
    links:
      - nextcloud-db
    volumes:
      - nextcloud-html:/var/www/html
      - nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-user
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}


networks:
  frontend:
    driver: ipvlan
    driver_opts:
      parent: "eth0.60"
      name: ipvlan60
    ipam:
      config:
        - subnet: 10.100.60.0/24
          gateway: 10.100.60.1
          ip_range: 10.100.60.50/28

  backend:
    driver: bridge
    internal: true
    
