version: "3.9"

networks:
  vlan_80:
    driver: macvlan # Otherwise PiHole and other containers cannot resolve DNS internally due to NAT issue within Docker
    # driver: ipvlan
    driver_opts:
      parent: ${NETWORK_DEVICE}.${METAL_VLAN_ID}
      name: macvlan${METAL_VLAN_ID}
    ipam:
      config:
        - subnet: 10.100.${METAL_VLAN_ID}.0/24
          gateway: ${METAL_GATEWAY}
          ip_range: 10.100.${METAL_VLAN_ID}.192/26 # 192-255
          # aux_addresses:
          #   reserved: 10.100.${METAL_VLAN_ID}.1
          #   dns: 10.100.${METAL_VLAN_ID}.3

  vlan_20:
    driver: macvlan # Otherwise PiHole container cannot resolve DNS internally due to NAT issue within Docker
    driver_opts:
      parent: ${NETWORK_DEVICE}.${THINGS_VLAN_ID}
      name: macvlan${THINGS_VLAN_ID}
    ipam:
      config:
        - subnet: 10.100.${THINGS_VLAN_ID}.0/24
          gateway: ${THINGS_GATEWAY}
          ip_range: 10.100.${THINGS_VLAN_ID}.12/32

  traefik_proxy:
    driver: bridge
    internal: true

  metrics:
    driver: bridge
    internal: true

  internet:
    driver: bridge

services:
  do-nothing:
    image: jhnrn/do-nothing:latest
    restart: unless-stopped
    networks:
      vlan_20:
      vlan_80:
      traefik_proxy:
      metrics:
      internet: