version: '3'

services:
  nextcloud-db:
    image: mariadb
    restart: always
    networks:
      - backend
    expose:
      - "3306"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /z-ip/configuration/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-user

  nextcloud-app:
    image: nextcloud
    restart: always
    networks:
      frontend_vlan60:
          ipv4_address: "10.100.60.49"
      backend:
    ports:
      - 8080:80
    links:
      - nextcloud-db
    volumes:
      - /z-ip/configuration/nextcloud/html:/var/www/html
      - /z-archives/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud-user
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}

  plex:
    image: plexinc/pms-docker
    restart: always
    hostname: plex-server
    networks:
      frontend_vlan60:
          ipv4_address: "10.100.60.50"
    volumes:
      - /z-ip/configuration/plex:/config
      - /z-ip/configuration/plex:/transcode
      - /z-archives/media:/data
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=33
      - PLEX_GID=33

  caddy:
    image: jhnrn/caddy-linux
    restart: always
    hostname: caddy-server
    networks:
      frontend_vlan60:
          ipv4_address: "10.100.60.12"
    environment:
      - DNS_API_KEY=${DNS_API_KEY}
    volumes:
      - /z-ip/configuration/caddy-docker/Caddy/Caddyfile:/etc/caddy/Caddyfile
      - /z-ip/configuration/caddy-docker/data:/data
      - /z-ip/configuration/caddy-docker/logs:/logs
      - /z-ip/configuration/caddy-docker/config:/config

networks:
  frontend_vlan60:
    driver: ipvlan
    driver_opts:
      parent: "eth0.60"
      name: ipvlan60
    ipam:
      config:
        - subnet: 10.100.60.0/24
          gateway: 10.100.60.1
          ip_range: 10.100.60.50/28

  backend:
    driver: bridge
    internal: true