version: "3.9"

networks:
  traefik_proxy:
    internal: true

  01-transit_80-net:
    driver: macvlan # Otherwise PiHole container cannot resolve DNS internally due to NAT issue within Docker
    # driver: ipvlan
    driver_opts:
      # ipvlan_mode: l2
      parent: ${NETWORK_DEVICE}.${METAL_VLAN_ID}
      name: macvlan${METAL_VLAN_ID}
    ipam:
      config:
        - subnet: 10.100.${METAL_VLAN_ID}.0/24
          gateway: 10.100.${METAL_VLAN_ID}.2
          ip_range: 10.100.${METAL_VLAN_ID}.128/26 # 128-191
          # aux_addresses:
          #   reserved: 10.100.${METAL_VLAN_ID}.1
          #   dns: 10.100.${METAL_VLAN_ID}.3

services:
  dns-upstream:
    image: jhnrn/cloudflared:latest
    container_name: "dns-upstream-${METAL_VLAN_NAME}"
    command: proxy-dns
    restart: always
    environment:
      TZ: ${TZ}    
      TUNNEL_METRICS: "0.0.0.0:49312"
      TUNNEL_DNS_ADDRESS: "0.0.0.0"
      TUNNEL_DNS_PORT: ${TUNNEL_DNS_PORT}
      TUNNEL_DNS_UPSTREAM: ${TUNNEL_DNS_UPSTREAM}
    networks:
      01-transit_80-net:
    healthcheck:
      test: dig +short @127.0.0.1 -p${TUNNEL_DNS_PORT} cloudflare.com A || exit 1
      # test: 'curl --http2 -H "accept: application/dns-json" "https://1.1.1.1/dns-query?name=cloudflare.com"  || exit 1'
      interval: 30s
      timeout: 5s
      retries: 2
    labels:
      - autoheal=true

  pihole:
    container_name: pihole-${METAL_VLAN_NAME}
    hostname: pihole-${METAL_VLAN_NAME}
    image: pihole/pihole:dev
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # ports:
      # - "53:53/tcp"
      # - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "80:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PIHOLE_DNS_: dns-upstream#${TUNNEL_DNS_PORT}
      # Listen on all interfaces and permit all origins
      # This allows Pihole to work in this setup and when answering across VLANS,
      # but do not expose pi-hole to the internet!
      DNSMASQ_LISTENING: local
      DNS_BOGUS_PRIV: true
      DNS_FQDN_REQUIRED: true
      DHCP_ACTIVE: true
      DHCP_START: 10.100.${METAL_VLAN_ID}.${DHCP_START_OCTET:-201}
      DHCP_END: 10.100.${METAL_VLAN_ID}.${DHCP_END_OCTET:-251}
      DHCP_ROUTER: 10.100.${METAL_VLAN_ID}.2
      PIHOLE_DOMAIN: ${DOMAIN}
      DHCP_LEASETIME: 24
      WEBTHEME: default-auto
    # Volumes store your data between container upgrades
    volumes:
      - ${DATA_STORAGE}/pihole/${METAL_VLAN_NAME}/pihole:/etc/pihole
      - ${DATA_STORAGE}/pihole/${METAL_VLAN_NAME}/dnsmasq.d:/etc/dnsmasq.d
      - ${DATA_STORAGE}/pihole/global/custom.list:/etc/pihole/custom.list
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      01-transit_80-net:
        ipv4_address: ${METAL_PIHOLE_IP_ADDRESS}
    dns:
      - 127.0.0.1        
    restart: unless-stopped
    depends_on:
      - dns-upstream
    healthcheck:
      test: ping -c 1 bing.com || exit 1
      # test: dig +short @127.0.0.1 pi.hole || exit 1
      interval: 30s
      retries: 5
    labels:
      - homepage.group=DNS
      - homepage.weight=1000
      - homepage.name=Pihole-metal
      - homepage.icon=pi-hole.png
      - homepage.href=http://${METAL_PIHOLE_IP_ADDRESS}/admin
      - homepage.description=for ${METAL_VLAN_NAME}
      - homepage.widget.type=pihole
      - homepage.widget.key=${PIHOLE_TOKEN}
      - homepage.widget.url=http://${METAL_PIHOLE_IP_ADDRESS}
      # - homepage.widget.fields=["queries", "blocked", "gravity"]

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: "cloudflared-tunnel"
    hostname: cloudflared-tunnel
    user: $PUID:$PGID
    restart: always
    networks:
      01-transit_80-net:
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    command:
      - tunnel
      - --no-autoupdate
      - run 
      - --token
      - ${CLOUDFARED_TOKEN}
    labels:
      - homepage.group=Network
      - homepage.weight=2000
      - homepage.name=Cloudflared tunnel
      - homepage.description=for Metal
      - homepage.icon=cloudflare-zero-trust.png
      - homepage.widget.type=cloudflared
      - homepage.widget.accountid=${CLOUDFLARED_TUNNEL_ACCOUNTID}
      - homepage.widget.tunnelid=${CLOUDFLARED_TUNNEL_TUNNELID_1}
      - homepage.widget.key=${CLOUDFLARE_TUNNEL_API_READ_TOKEN}      

  plex-music:
    image: plexinc/pms-docker:plexpass
    hostname: plex-music
    container_name: plex-music
    labels:
      traefik.enable: true
      traefik.http.routers.plex.rule: "Host(`music.${DOMAIN}`)"
      traefik.http.routers.plex.entrypoints: web,web-secure
      traefik.http.routers.plex.tls.certresolver: "certificato"
      traefik.http.services.plex.loadbalancer.server.port: 32400
      homepage.group: Metal
      homepage.weight: 2000
      homepage.name: Plex
      homepage.icon: plex.png
      homepage.href: https://music.${DOMAIN}/
      homepage.description: for music
      homepage.widget.type: plex
      homepage.widget.url: http://${PLEXMUSIC_IP_ADDRESS}:32400
      homepage.widget.key: ${PLEX_MUSIC_TOKEN}
      autoheal: true
    networks:
      01-transit_80-net:
        ipv4_address: ${PLEXMUSIC_IP_ADDRESS}
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - HOSTNAME=music.${DOMAIN}
    volumes:
      - ${DATA_STORAGE}/plex/config:/config
      - ${MUSIC}:/media/music
    restart: unless-stopped

  librespeed:
    image: adolfintel/speedtest
    hostname: librespeed
    container_name: librespeed
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      - MODE=standalone
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.rule=Host(`speedtest.${DOMAIN}`)"
      - "traefik.http.routers.librespeed.tls.certresolver=certificato"
      - traefik.http.routers.librespeed.entrypoints=web,web-secure
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"

  speedtest_tracker-db:
    image: postgres:15
    container_name: speedtest_tracker-db
    restart: always
    user: $PUID:$PGID
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER=${SPEEDTEST_TRACKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SPEEDTEST_TRACKER_POSTGRES_PASSWORD}
    volumes:
      - ${DATA_STORAGE}/speedtest-tracker-alexjustesen/db:/var/lib/postgresql/data
    networks:
      traefik_proxy:

  speedtest_tracker:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    hostname: speedtest-tracker
    container_name: speedtest_tracker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest_tracker-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=${SPEEDTEST_TRACKER_POSTGRES_USER}
      - DB_PASSWORD=${SPEEDTEST_TRACKER_POSTGRES_PASSWORD}
      - TZ=${TZ}
      - APP_DEBUG=${SPEEDTRACKER_APP_DEBUG:-false}
      - APP_KEY=${SPEEDTRACKER_APP_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_STORAGE}/speedtest-tracker-alexjustesen/config:/config
      - ${DATA_STORAGE}/speedtest-tracker-alexjustesen/web:/etc/ssl/web
    depends_on:
      - speedtest_tracker-db
    networks:
      traefik_proxy:
      01-transit_80-net:
        ipv4_address: ${METAL_SPEEDTRACKER_IP_ADDRESS}
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-tracker.rule=Host(`speedtracker.${DOMAIN}`)"
      - "traefik.http.routers.speedtest-tracker.tls.certresolver=certificato"
      - "traefik.http.services.speedtest-tracker.loadbalancer.server.port=80"
      - traefik.http.routers.speedtest-tracker.entrypoints=web,web-secure
      - homepage.group=Network
      - homepage.weight=10000
      - homepage.name=Speedtest
      - homepage.icon=speedtest-tracker.png
      - homepage.href=https://speedtracker.${DOMAIN}/
      - homepage.description=Speedtest
      - homepage.widget.type=speedtest
      - homepage.widget.url=https://speedtracker.${DOMAIN}
      # - homepage.widget.fields=["download", "upload", "ping"]

  homepage:
    image: ghcr.io/gethomepage/homepage:main
    container_name: homepage
    hostname: homepage
    user: $PUID:$PGID
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DATA_STORAGE}/homepage:/app/config # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations      
    networks:
      01-transit_80-net:
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: "Host(`www.${DOMAIN}`)"
      traefik.http.routers.homepage.tls.certresolver: "certificato"
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.http.routers.homepage.entrypoints: web,web-secure

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
        - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
        - 2375:2375
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    networks:
      01-transit_80-net:
        ipv4_address: ${METAL_DOCKERPROXY_IP_ADDRESS}
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    hostname: qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8220
    volumes:
      - ${DATA_STORAGE}/qbittorrent:/config
      - ${TORRENTS}:/downloads #optional
    networks:
      01-transit_80-net:
        ipv4_address: ${QBITTORRENT_IP_ADDRESS}
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`torrent.${DOMAIN}`)
      - traefik.http.routers.qbittorrent.tls.certresolver=certificato
      - traefik.http.routers.qbittorrent.entrypoints=web,web-secure
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8220
      - homepage.group=Metal
      - homepage.name=Qbittorrent
      - homepage.weight=4000
      - homepage.icon=qbittorrent.png
      - homepage.href=https://torrent.${DOMAIN}/
      - homepage.description=Qbittorrent
      - homepage.widget.type=qbittorrent
      - homepage.widget.username=admin
      - homepage.widget.password=${QBITTORRENT_PASSWORD}
      - homepage.widget.url=https://torrent.${DOMAIN}
      # - homepage.widget.fields=["leech","download", "seed", "upload"]

  overseerr:
    image: sctx/overseerr:latest
    hostname: overseerr
    container_name: overseerr
    user: $PUID:$PGID
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 #optional
    volumes:
      - ${DATA_STORAGE}/overseerr:/app/config
    restart: unless-stopped
    networks:
      01-transit_80-net:
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=Host(`fetch.${DOMAIN}`)
      - traefik.http.routers.overseerr.tls.certresolver=certificato
      - traefik.http.routers.overseerr.entrypoints=web,web-secure
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - homepage.group=Metal
      - homepage.weight=3000
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://fetch.${DOMAIN}/
      - homepage.description=Overseerr
      - homepage.widget.type=overseerr
      - homepage.widget.key=${OVERSEERR_API_KEY}
      - homepage.widget.url=https://fetch.${DOMAIN}
      # - homepage.widget.fields=["pending", "approved", "available", "processing"]

  autoheal:
    image: jhnrn/docker-autoheal:latest
    container_name: "autoheal"
    restart: always
    environment:
      TZ: ${TZ}    
      AUTOHEAL_CONTAINER_LABEL: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none

  glances:
    image: nicolargo/glances:dev
    container_name: glances
    restart: unless-stopped
    pid: host
    privileged: true
    networks:
      01-transit_80-net:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${DATA_STORAGE}/glances/glances.conf:/glances/conf/glances.conf
    environment:
      - GLANCES_OPT=-C /glances/conf/glances.conf -w
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.rule=Host(`glancesmb.${DOMAIN}`)
      - traefik.http.routers.glances.tls.certresolver=certificato
      - traefik.http.routers.glances.entrypoints=web,web-secure
      - traefik.http.services.glances.loadbalancer.server.port=61208

  whoogle-search:
    image: ${WHOOGLE_IMAGE:-benbusby/whoogle-search}
    container_name: whoogle-search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    #environment: # Uncomment to configure environment variables
      # Basic auth configuration, uncomment to enable
      #- WHOOGLE_USER=<auth username>
      #- WHOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- WHOOGLE_PROXY_USER=<proxy username>
      #- WHOOGLE_PROXY_PASS=<proxy password>
      #- WHOOGLE_PROXY_TYPE=<proxy type (http|https|socks4|socks5)
      #- WHOOGLE_PROXY_LOC=<proxy host/ip>
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values.
      #- WHOOGLE_ALT_TW=farside.link/nitter
      #- WHOOGLE_ALT_YT=farside.link/invidious
      #- WHOOGLE_ALT_IG=farside.link/bibliogram/u
      #- WHOOGLE_ALT_RD=farside.link/libreddit
      #- WHOOGLE_ALT_MD=farside.link/scribe
      #- WHOOGLE_ALT_TL=farside.link/lingva
      #- WHOOGLE_ALT_IMG=farside.link/rimgo
      #- WHOOGLE_ALT_WIKI=farside.link/wikiless
      #- WHOOGLE_ALT_IMDB=farside.link/libremdb
      #- WHOOGLE_ALT_QUORA=farside.link/quetre
    #env_file: # Alternatively, load variables from whoogle.env
      #- whoogle.env
    # ports:
    #   - 5000:5000
    networks:
      01-transit_80-net:
        ipv4_address: ${METAL_WHOOGLE_IP_ADDRESS}
    dns:
      - ${METAL_PIHOLE_IP_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoogle.rule=Host(`whoogle.${DOMAIN}`)
      - traefik.http.routers.whoogle.tls.certresolver=certificato
      - traefik.http.routers.whoogle.entrypoints=web,web-secure
      - traefik.http.services.whoogle.loadbalancer.server.port=5000

  dozzle:
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    environment:
      DOZZLE_REMOTE_HOST: tcp://${HEAVYMETAL_DOCKERPROXY_IP_ADDRESS}:2375,tcp://${METAL_DOCKERPROXY_IP_ADDRESS}:2375
    networks:
      # Need the transit network to talk to other docker host(s)
      01-transit_80-net:
    labels:
      - homepage.group=Monitoring
      - homepage.description=Docker log monitoring
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=https://dockerlogs.${DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dockerlogs.${DOMAIN}`)
      - traefik.http.routers.dozzle.tls.certresolver=certificato
      - traefik.http.routers.dozzle.entrypoints=web,web-secure
      - traefik.http.services.dozzle.loadbalancer.server.port=8080

  cobalt-api:
    image: ghcr.io/wukko/cobalt:latest
    restart: unless-stopped
    container_name: cobalt-api
    init: true
    # if container doesn't run detached on your machine, uncomment the next line:
    #tty: true
    networks:
      traefik_proxy:
      01-transit_80-net:
    # ports:
      # - 9000:9000/tcp
      # if you're using a reverse proxy, uncomment the next line:
      #- 127.0.0.1:9000:9000
    environment:
      - apiPort=9000
      # replace apiURL with your instance's target url in same format
      - apiURL=https://ytdl-api.${DOMAIN}/
      # replace apiName with your instance's distinctive name
      - apiName=ytdl-api
      # if you want to use cookies when fetching data from services, uncomment the next line
      #- cookiePath=/cookies.json
      # see src/modules/processing/cookie/cookies_example.json for example file.
    # labels:
    # if you want to use cookies when fetching data from services, uncomment volumes and next line
    #volumes:
        #- ./cookies.json:/cookies.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytdl-api.rule=Host(`ytdl-api.${DOMAIN}`)
      - traefik.http.routers.ytdl-api.tls.certresolver=certificato
      - traefik.http.routers.ytdl-api.entrypoints=web,web-secure
      - traefik.http.services.ytdl-api.loadbalancer.server.port=9000

  cobalt-web:
    image: ghcr.io/wukko/cobalt:latest
    restart: unless-stopped
    container_name: cobalt-web
    init: true
    # if container doesn't run detached on your machine, uncomment the next line:
    #tty: true
    networks:
      traefik_proxy:
    # ports:
        # - 9001:9001/tcp
        # if you're using a reverse proxy, uncomment the next line:
        # - 127.0.0.1:9001:9001
    environment:
        - webPort=9001
        # replace webURL with your instance's target url in same format
        - webURL=https://ytdl.${DOMAIN}/
        # replace apiURL with preferred api instance url
        - apiURL=https://ytdl-api.${DOMAIN}/

    labels:
      - traefik.enable=true
      - traefik.http.routers.ytdl.rule=Host(`ytdl.${DOMAIN}`)
      - traefik.http.routers.ytdl.tls.certresolver=certificato
      - traefik.http.routers.ytdl.entrypoints=web,web-secure
      - traefik.http.services.ytdl.loadbalancer.server.port=9001
