version: "3.5"

networks:
  transit_zero-net:
    driver: macvlan
    driver_opts:
      parent: eth0 # soon changes to eth0.1
      name: macvlan1 # soon changes to macvlan1
    ipam:
      config:
        - subnet: 10.100.0.0/24
          gateway: ${TRANSIT0_GATEWAY_IP_ADDRESS}
          ip_range: 10.100.0.0/29        # 10.100.0.48 - 10.100.0.51
services:
  http-server:
    image: jhnrn/http-server-linux:latest
    container_name: "http-server"
    restart: always
    ports:
      - "3000:3000"

  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.9
    restart: unless-stopped
    stop_grace_period: 60s
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=${TZ}
    volumes:
      - ${DATA_STORAGE}/omada/data:/opt/tplink/EAPController/data
      - ${DATA_STORAGE}/omada/logs:/opt/tplink/EAPController/logs
    networks:
      transit_zero-net:
        ipv4_address: ${OMADA_IP_ADDRESS} 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omada.rule=Host(`omada.${DOMAIN}`)"
      - "traefik.http.routers.omada.tls.certresolver=certificato"
      - "traefik.http.services.omada.loadbalancer.server.port=8043"