name: heavymetal-host-network
networks:
  networks_vlan_80:
    external: true
  networks_vlan_30:
    external: true

services:

  samba:
    image: crazymax/samba
    container_name: samba
    hostname: docker_samba
    # network_mode: host
    networks:
      networks_vlan_80:
        ipv4_address: ${SAMBA_IP_ADDRESS}
      networks_vlan_30:
        ipv4_address: ${SAMBA_VLAN30_IP_ADDRESS}
    volumes:
      # - ./data:/data
      # - ./public:/samba/public
      # - ./share:/samba/share
      # - ./foo:/samba/foo
      - ${APPDATA}/samba/data:/data
      - ${APPDATA}/samba/public:/samba/public
      # - ${TORRENTS}:/samba/downloads
      # - ${MOVIES}:/samba/media/Movies
      # - ${TVSHOWS}:/samba/media/Series
      # - ${MUSIC}:/samba/media/Music
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    environment:
      TZ: ${TZ}
      SAMBA_LOG_LEVEL: 0
      WSDD2_ENABLE: ${WSDD2_ENABLE}
      WSDD2_NETBIOS_NAME: ${WSDD2_NETBIOS_NAME}
      PUID: 33
      PGID: 33
    restart: unless-stopped
