name: Caddy - Creates executable for Windows platform

on: workflow_dispatch 

jobs:

  build:
    runs-on: windows-latest
    env:
      GOOS: windows
      GOARCH: amd64
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build xcady
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Adds GOBIN to PATH
      run: |
        $env:Path = $env:Path + '; ' + ${env:GOPATH} + '; ' + ${env:GOPATH} + '\bin'

    - name: xcaddy
      run: xcaddy build --output .output/caddy.exe   --with github.com/caddy-dns/cloudflare
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: .output/*
        if-no-files-found: error
        
  