name: Caddy - Build  docker image

on: workflow_dispatch

defaults:
  run:
    working-directory: caddy

jobs:

  build:

    runs-on: windows-latest
    env:
      IMAGE_NAME: caddy-win
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    # - name: Enable experimental features for the Docker daemon and CLI
    #   run: |
    #       Get-Content -Path c:\ProgramData\docker\config\daemon.json
    #       '{', '  "experimental": true', '}' | Set-Content -Path c:\ProgramData\docker\config\daemon.json
    #       Get-Content -Path c:\ProgramData\docker\config\daemon.json
    #       Restart-Service docker
    #       docker version
    #       docker info

    # - name: Restart Docker daemon
    #   run: |
    #       docker version
    #       docker info

    - name: Test
      run: Get-ChildItem -Recurse -Path 'c:\programdata'

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:$(date +%Y%m%d).${{ github.run_number }} --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest

    - name: Docker push as latest
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest

    - name: Docker push with date tag
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:$(date +%Y%m%d).${{ github.run_number }}
