name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print new build number
      run: echo "Build number is ${env:BUILD_NUMBER}"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/caddy-win:${env:BUILD_NUMBER} --tag ${{secrets.DOCKERHUB_USERNAME}}/caddy-win:latest

    - name: Docker push as latest
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/caddy-win:latest

    - name: Docker push with date tag
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/caddy-win:${env:BUILD_NUMBER}
