name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/caddy-win:$(date +%s) --tag ${{secrets.DOCKERHUB_USERNAME}}/caddy-win:latest

    - name: Docker push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/caddy-win
