name: sonarr - Build docker Image for Sonarr

on: workflow_dispatch

defaults:
  run:
    working-directory: sonarr

jobs:

  build:

    runs-on: self-hosted
    env:
      IMAGE_NAME: sonarr-windows
      BASE_VERSION: ltsc2022
      DATE_STAMP: $(date +%Y%m%d)

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build . --no-cache --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }} --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest --build-arg BASE=${{env.BASE_VERSION}} 

    - name: Docker push images
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }}
