name: tailscale - Build custom version of tailscale with ability to set exit node using envvar

on: 
  schedule:
    - cron: "20 3 * * 4"   # At 03:20 on Thursday.
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

defaults:
  run:
    working-directory: tailscale

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATE_STAMP: $(date +"%Y%m%d")
      IMAGE_NAME: tailscale
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build . \
          --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }} \
          --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest

    - name: Docker push images
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }}
