name: vsbuildtools2019(ltsc2019) - Builds docker image for building VS2017 C++ and .NET Framework projects

on: workflow_dispatch

defaults:
  run:
    working-directory: buildtools

jobs:

  build:

    runs-on: windows-2019
    env:
      IMAGE_NAME: vsbuildtools2019-ltsc2019
      DATE_STAMP: $(date +%Y%m%d)

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build . --no-cache --file Dockerfile.vsbuildtools2019.ltsc2019 --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }} --tag ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest

    - name: Docker push images
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.DATE_STAMP }}.${{ github.run_number }}
